# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-24 23:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RRHH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ingrese su Nombre: ', max_length=50)),
                ('telphone', models.CharField(help_text='Ingrese su numero telefonico: ', max_length=10)),
                ('sex', models.CharField(help_text='Seleccione su genero: ', max_length=1)),
                ('bday', models.DateField()),
            ],
        ),
    ]
